### ISSUE TITLE
Secure SSL certificates and Java keystores and truststores

### ISSUE THREAD

**Issue by Nuttymoon** [TOSIT-IO/tdp-collection#390]
Related to #387 

As a quick win on SSL security, we can first restrict permissions on:
- SSL certificates:
  - `/etc/ssl/certs/$(hostname).(key|pem|p12)`: `600 root:root`
- Java keystore/truststore:
  - `/etc/ssl/certs/keystore.jks`: `640 root:hadoop`
  - `/etc/ssl/certs/truststore.jks`: `644 root:hadoop`
- Ranger plugins `install.properties`:
  - `/opt/tdp/ranger-*-plugin/install.properties`: `640 root:hadoop`

I also think that prefixing the keystores and truststores with `hadoop-` could clarify what it is used for.

**Comment by leopaul36** [comment]
FYI @rpignolet gave some thoughts about this at https://github.com/TOSIT-IO/tdp-collection/issues/98

- The permissions of `/etc/ssl/certs/*` are outside of the collection scope since the collection expect those to already be here. Thought I agree on setting these to `600 root:root`.

- We can all agree on the keystore / truststores owners and permissions. The truststore could be root:root as mentioned by @rpignolet.

I am not really favorable to adding `hadoop` since it the main idea was to share it with all the components. If it's not clear to users what these are we should individualize these into each components' configuration dir.

**Comment by Nuttymoon** [comment]
> FYI @rpignolet gave some thoughts about this at #98
> 
>     * The permissions of `/etc/ssl/certs/*` are outside of the collection scope since the collection expect those to already be here. Thought I agree on setting these to `600 root:root`.
> 
>     * We can all agree on the keystore / truststores owners and permissions. The truststore could be root:root as mentioned by @rpignolet.
> 
> 
> I am not really favorable to adding `hadoop` since it the main idea was to share it with all the components. If it's not clear to users what these are we should individualize these into each components' configuration dir.

My bad, I didn't check existing issues on this topic. I am going to label this issue as a duplicate.
